### ISSUE TITLE
login screen keeps

### ISSUE THREAD

**Issue by Schwertspize** [jonan/ForkHub#94] opened 2015-11-09 06:43 UTC
workaround: login once and close the app

**Comment by jonan** [comment] 2015-11-09 10:20
Are you using F2A?

**Comment by Schwertspize** [comment] 2015-11-09 10:38
nope

**Comment by jonan** [comment] 2015-11-09 14:48
It's working fine here, how can you reproduce it exactly?

**Comment by jonan** [comment] 2015-11-25 16:39
I can't reproduce this issue so I'm closing it.

Feel free to reopen it if you can add more details.

**Closed by jonan** 2015-11-25 16:39 UTC
