### ISSUE TITLE
Raw markdown shown in news tab

### ISSUE THREAD

**Issue by DerDakon** [jonan/ForkHub#188] opened 2016-05-09 17:05 UTC
Entries in the news tab that contain markdown are shown as plain text, i.e. the raw markdown code is visible. It would be better to show only the textual representation, i.e. the link text, but not the URL, and no images.

**Comment by jonan** [comment] 2016-05-10 11:06
Duplicate of #87

**Closed by jonan** 2016-05-10 11:06 UTC
