### ISSUE TITLE
Not all search results are shown

### ISSUE THREAD

**Issue by KOLANICH** [jonan/ForkHub#327] opened 2017-10-03 18:01 UTC
When I search through ForkHub I get incomplete search results. When I know the issue I look for I have to narrow search request. When I need to see whole results, I have to use web interface.

**Comment by licaon-kter** [comment] 2017-10-03 18:16
/duplicate of #326

You did search before posting, right? :) :)

**Comment by KOLANICH** [comment] 2017-10-03 18:46
Don't you think that ```Search finds nothing``` is a bit different from "search finds something, but not the everything it must find"?

**Comment by licaon-kter** [comment] 2017-10-03 22:10
My description might be incomplete indeed. Thanks

/still duplicate though

**Comment by jonan** [comment] 2017-10-04 10:26
Lets close this issue and leave #326

**Closed by jonan** 2017-10-04 10:26 UTC
